version: "3.9"
services:
    db:
        container_name: mongo
        image: "mongo"
        restart: always
        ports:
            - 27017:27017
        networks:
            - middle
    web:
        container_name: web
        build: .
        restart: always
        ports:
            - 2000:2000
        depends_on:
            - db
        environment:
            - MONGO_URI=mongodb://db:27017/myapp
        networks:
            - middle
    
networks:
    middle:
        driver: bridge

