version: "3.9"
services:
    mongo:
        image: "mongo"
        restart: always
        ports:
            - "27017:27017"
    web:
        build: .
        volumes:
            - .:/app
        ports:
            - "2000:2000"

